[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
arbitrum_sepolia = { key = "${ARBITRUM_SEPOLIA_RPC_URL}", url = "https://api-sepolia.arbiscan.io/" }
base_sepolia = { key = "${BASE_SEPOLIA_RPC_URL}", url = "https://api-sepolia.basescan.io/" }
 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
