name: Forge CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive   # grabs lib/ if you committed it

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1     # 1-line install
        with:
          version: stable        # or nightly / v0.3.9 etc.
          cache: true            # keep RPC responses

      - name: Run tests
        run: forge test -vv
